typography_spectrum: 0.3848446076735854
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2590289767831564
  lightness: 0.14220454031601548
  saturation: 0.4317061163019389
  rhythmicContrast: 0.5240881803911179
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1529363279696554
analytics:
  google: null
  facebook: null
  twitter: null
name: guysmileemakesnoise
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Music & Sound
description: what is it all about?
purpose: []
